### ISSUE TITLE
Update masking function to consider missing inputs

### ISSUE THREAD

**Issue by gabrieltseng** [WorldCereal/presto-worldcereal#1]
Currently, (truly) missing values are still passed to the model in `train.py`. If a value is missing it should get masked in the masking function and also in the loss. 

- [ ] Masking function accepts a (true) mask as input, and only masks an additional number of tokens
- [ ] Loss ignores this true mask during training
- [ ] Test to make sure this works as expected

One edge case to deal with is if a higher number of true values are masked than the masking ratio - those points might have to be ignored, so we should see how often this is the case.

**Comment by kvantricht** [comment]
An additional TODO when those things are in place is to make sure `WorldCerealDataset` actually masks nodata values by making the required changes. That includes setting setting desired destination nodata value for [optical](https://github.com/WorldCereal/presto-worldcereal/blob/main/src/dataset.py#L64), [SAR ](https://github.com/WorldCereal/presto-worldcereal/blob/main/src/dataset.py#L87) and [meteo ](https://github.com/WorldCereal/presto-worldcereal/blob/main/src/dataset.py#L114) data, and then finally properly [updating the mask](https://github.com/WorldCereal/presto-worldcereal/blob/main/src/dataset.py#L158:L169) for these nodata elements.
