### ISSUE TITLE
Try Presto on dekadal inputs

### ISSUE THREAD

**Issue by kvantricht** [WorldCereal/presto-worldcereal#18]
Presto is trained on monthly composited inputs. We want to experiment what pretrained Presto does on dekadal (10d) inputs natively and check what need to do in next steps.

- [x] Prepare dekadal inputs for WorldCereal Presto inputs
- [x] Explicit setting of the month vector
- [x] Experiment on Presto results on downstream task

**Comment by gabrieltseng** [comment]
> Explicit setting of the month vector

This might not be necessary - an (even) easier test would be to just pass the month vector as is, since the positional encoding will also capture relative positions within the month.

**Comment by kvantricht** [comment]
@giollimirgia could you provided an update on what still needs to be done to close this issue?

**Comment by giollimirgia** [comment]
the code for Presto fine tune on the 10D WorldCereal data is available on the dataset-10days branch. I have fine-tuned the native Presto on such 10D data and got some first results that should be compared to the monthly WorldCereal Presto. We can close this issue and proceed with the comparison.
