### ISSUE TITLE
Add hierarchical head on top of Presto encoder for crop type classification

### ISSUE THREAD

**Issue by kvantricht** [WorldCereal/presto-worldcereal#27]

**Comment by gabrieltseng** [comment]
#71 closes this - @cbutsko implemented a hierarchical catboost classifier

**Comment by cbutsko** [comment]
After discussions, it was decided that current implementation of hierarchical classification as in [here](https://github.com/WorldCereal/presto-worldcereal/blob/croptype/presto/hierarchical_classification.py) is enough.
