### ISSUE TITLE
Speed up Presto based on new Pytorch tools

### ISSUE THREAD

**Issue by kvantricht** [WorldCereal/presto-worldcereal#30]

**Comment by kvantricht** [comment]
@gabrieltseng I'm wondering what kind of speedup we could expect for this, mostly for inference. What's your perception of time it would take and the gain we get from it?

**Comment by kvantricht** [comment]
@gabrieltseng I did a local test with just an upgrade from `torch==2.0.0` to `torch==2.3.1` and had a 45% reduction in processing time. What would be the caveats to work with this version instead? From inference side, I think it's a no brainer to do the upgrade, results look identical.

**Comment by gabrieltseng** [comment]
Upgrading shouldn't be a problem, but we can add a test to make sure we are getting similar numbers

**Comment by gabrieltseng** [comment]
- [x] Upgrade pytorch version done in #80 
- [ ] Investigate model compilation tools for speedup

**Comment by kvantricht** [comment]
This is being addressed in https://github.com/WorldCereal/presto-worldcereal/pull/88, however, before this can be safely merged, we need to:

- [x] add a test that confirms that original vs compiled encoder return the same result

Reason I add this is because I may have seen a case where predictions were different but this could have been due to some other thing. Therefore, it needs to be tested.

**Comment by cbutsko** [comment]
The test is already there https://github.com/WorldCereal/presto-worldcereal/blob/aa2f74d9de2d5f8d9c92c3ef6fc0765f83f4d17f/tests/test_inference.py#L21
