### ISSUE TITLE
Generate Presto features for the spatial inference patches

### ISSUE THREAD

**Issue by kvantricht** [WorldCereal/presto-worldcereal#31]
@CButsko as you were already showing spatial inference, is still needed? Could you put here in this case what you need exactly?

**Comment by kvantricht** [comment]
> [@cbutsko](https://github.com/cbutsko) as you were already showing spatial inference, is still needed? Could you put here in this case what you need exactly?

@cbutsko gentle reminder ;-)

**Comment by cbutsko** [comment]
yes, it'd still be helpful to have! currently test patches in the .nc format contain 17 data variables: optical/sar/meteo/dem features for 12 monthly TS. It'd be great to have along that presto embeddings too, so that I could use them to make inference with model trained with presto features.

**Comment by kvantricht** [comment]
OK I will work on that. I'll add both the pretrained and finetuned presto embeddings for completeness.

**Comment by kvantricht** [comment]
@cbutsko it's not that convenient to add 128 presto features to the existing netcdfs, so for now I created separate files which you can match based on their name. Could you check if the files here serve your needs? `/vitodata/worldcereal/data/openeo/inputs_presto/preprocessed_out/presto_embeddings/finetuned`
