### ISSUE TITLE
Define additional evaluation metrics

### ISSUE THREAD

**Issue by gabrieltseng** [WorldCereal/presto-worldcereal#4]
In particular, we are aiming to capture the spatial and temporal stability of the model. 

Potential ideas include:
- [x] Measuring performance as a function of year
- [x] Measuring performance as a function of AEZ
- [x] Measuring performance as a function of continent

**Comment by kvantricht** [comment]
As a bare minimum, we'd need [here](https://github.com/WorldCereal/presto-worldcereal/blob/main/src/dataset.py#L117) access to the `aez` of the sample and the `year` (defined by the year in which `end_date` is situated), e.g.
```
aez_id, year = row.aez_zoneid, int(row.end_date[:4])
```

but then this needs to passed on in many occasions and I don't know how sustainable this is, e.g. when at some point we come up with yet another attribute we could use for the eval task. @gabrieltseng what do you think?

As for the metrics, `F1`, `precision` and `recall` as implemented now seem like a good start for which we now need to include some of this spatial/temporal variability. 

Could we do a `groupby('aez')`, compute the metrics for each AEZ and then finally compute **macro avg** and **weighted avg** like you would normally do for multi-class metrics but in our case to describe consistency of the metric across AEZ?
We could then do the same for `groupby('year')`.

**Comment by gabrieltseng** [comment]
Hmm I wonder if an alternative would be to create multiple `WorldCerealEval`s for different years and AEZs and basically treat then as independent. 

Something like 

```python
eval_tasks = []
for id in train_df.aexz_zoneid.unique():
eval_tasks.append(WorldCerealEval(
    train_data=train_df[train_df.aez_zoneid == id]
    val_data=val_df[val_df.aez_zoneid == id]
))
...
for task in eval_tasks:
    results = full_eval.finetuning_results(model, ...)
```

**Comment by kvantricht** [comment]
Interesting idea, although I do think there's gonna be significant overhead and hence long running eval tasks. Also, this then means training the sklearn algorithms also per year and per AEZ which by definition is not something we want here with Presto, we want to train once on all data and only split up evaluation per AEZ/year so we know if the model is stable or not. Correct?

**Comment by gabrieltseng** [comment]
Ah yes - good point. I'll try re-writing the eval tasks so that it doesn't require retraining.

**Comment by gabrieltseng** [comment]
Assigning to @rubencart to implement

**Comment by rubencart** [comment]
For now I kept all the logic in the `WorldCerealEval` class, since the extra data we need is in the dataframe, and the eval class has access to this, so this seemed simpler. Let me know if you actually prefer a solution similar to
```python
list_of_val_partitions = [
    *[val_df[val_df.aez_zoneid == id] for id in train_df.aez_zoneid.unique()],
    ...
]
full_eval = WorldCerealEval(
    train_data=train_df,
    val_data=list_of_val_partitions,
))
results = full_eval.finetuning_results(model, ...)
```
