### ISSUE TITLE
Valid date for crop types

### ISSUE THREAD

**Issue by gabrieltseng** [WorldCereal/presto-worldcereal#47]
- Currently, two very similar timeseries might have two different crop type labels depending on when the sample was collected
- The `valid date` communicates to us when the sample was taken
- At a minimum this should be included in the model, perhaps to truncate the timeseries

**Comment by kvantricht** [comment]
@gabrieltseng could you provide an update on what we plan to do with this issue? It's in our project tracking but not sure what we expect on the short term.

**Comment by gabrieltseng** [comment]
It is currently being investigated in #49

**Comment by gabrieltseng** [comment]
#71 closes this issue
