### ISSUE TITLE
Seasonality check for specific regions

### ISSUE THREAD

**Issue by cbutsko** [WorldCereal/presto-worldcereal#50]
Using a simple `find_peaks` function from scipy, existing training data for WorldCereal was analysed. 12-month timeseries of NDVI were obtained for each cropland sample. As a result, each sample received a corresponding number of detected vegetation peaks. Then, for each country and each n_peaks value, a random subset of 100 samples was selected (if available) and plotted. 

Below is the list of countries where seasonality might require adjustment:
- Burkina Faso
- Mexico
- Mali
- Kazakhstan
- Uzbekistan
- Nigeria
- Sudan
- Senegal

And here are charts for visual clarity:
![Image](https://github.com/WorldCereal/presto-worldcereal/assets/10546825/e79cf6c5-d59c-431f-a5bd-4ced53d261d2)
![Image](https://github.com/WorldCereal/presto-worldcereal/assets/10546825/d5073459-bfca-4b9f-8e25-5ad4bff1c81c)
![Image](https://github.com/WorldCereal/presto-worldcereal/assets/10546825/3dfe308b-67ec-4a88-a40d-af1138860d21)
![Image](https://github.com/WorldCereal/presto-worldcereal/assets/10546825/9d82e2f5-2aa4-499e-8782-e9de190096a8)
![Image](https://github.com/WorldCereal/presto-worldcereal/assets/10546825/94e43316-ecc7-4f06-abcd-d96a81a9557f)
![Image](https://github.com/WorldCereal/presto-worldcereal/assets/10546825/b89c1524-59f0-4d71-a04c-e4a0379c67a1)
![Image](https://github.com/WorldCereal/presto-worldcereal/assets/10546825/f4a386d3-d58f-4200-b64f-9faae20bb8ab)
![Image](https://github.com/WorldCereal/presto-worldcereal/assets/10546825/7fea7908-76e5-4025-a9f4-940b905df6df)

More detailed findings can be found in [issue 13](https://github.com/WorldCereal/worldcereal-classification/issues/13) 

@MolettoLobos Can we check what seasons look like in the new version of crop calendar for these countries? It is also very likely that neighboring countries will have the same issue, however they are not included in this list as we don't have enough points there.

**Comment by kvantricht** [comment]
@cbutsko the Kazakhstan plot caught my attention because many of the curves are cut off. Any idea why? Is this 0 values you're now not showing?

**Comment by cbutsko** [comment]
@kvantricht yes, these are absent values. I suppose no clean imagery was available. The same situation can be seen in Latvia (one plot shows Oats recognized as crop, another one - those that are not recognized as crop) 
![Image](https://github.com/WorldCereal/presto-worldcereal/assets/10546825/287268f9-5e11-48c7-ae74-f95a9bb0f628)
![Image](https://github.com/WorldCereal/presto-worldcereal/assets/10546825/4de701d9-4605-43d9-9278-80d6d83b593a)

**Comment by cbutsko** [comment]
@MolettoLobos Italo, any thoughts or updates regarding this issue?

**Comment by MolettoLobos** [comment]
Hi Christina, sorry for late reply. For the season retrieval how are you retrieving the data? for SOS and EOS are you using the AEZ? or the raster with cropcalendars? In case the usage is the AEZ? In those countries the behaviour seems to be shifted, and such places like Mexico contains different type of crops. We can arrange a meeting to see what happens and understand better the behaviour. I think these parameters can be fixed with LSP incorporation

**Comment by kvantricht** [comment]
@MolettoLobos @cbutsko does this issue need to remain open or do we create other ones for specific required corrections?
