### ISSUE TITLE
Perform error analysis to distinguish temporary crops model deficiency from label ambiguity

### ISSUE THREAD

**Issue by kvantricht** [WorldCereal/presto-worldcereal#60]
A more detailed error analysis should be performed separately to understand what portion of errors can be attributed to the temporary crops model itself, and where there might be label ambiguity happening.

**Comment by kvantricht** [comment]
First version done, but will be repeated for the new runs after merging `croptype` into `main`.

**Comment by cbutsko** [comment]
Results are collected [here](https://docs.google.com/spreadsheets/d/1WA9T54SR3UW1DkML6dP1WG4Xp-znGrcHnLhOhpq-12g/edit?usp=sharing)

**Conclusions:**

- The classes that contribute to errors the most are the following: `pasture_meadows, non_cropland_incl_perennial, built_up`. 
- The classes with lowest Producer Accuracy are the following: `permanent_leguminous_crops, temporary_crops, permanent_crops, permanent_tree_shrub_flowers`
- ~10% of wheat and maize sample are wrongly predicted as not_crop. While certain part of these errors are true errors, the majority of them likely comes from bad labels (still need to look at division by country/ref_id)

**Comment by kvantricht** [comment]
This is interesting, we should keep these results for future reference!
