### ISSUE TITLE
Temporal tests - 30D to 10D Presto performance comparison on crop type task

### ISSUE THREAD

**Issue by giollimirgia** [WorldCereal/presto-worldcereal#61]
Excluded `CROPTYPE_LABEL` : 
```
[ 0, 991, 7900, 9900, 9998, # unspecified cropland 
 1910, 1900, 1920, 1000, # cereals
 11, 9910, 6212  # tmp crops ]
```

Test year: `2021`

Training, validation and test distributions 

<img src=https://github.com/WorldCereal/presto-worldcereal/assets/49987400/92567716-57ea-4294-b8f1-b40eac7ae103 alt="image" width="600" height="400">

Experiments:

- [x]  pretrained Presto (not fine tuned) + Catboost training on crop-type monthly data
- [x]  pretrained Presto (not fine tuned) + Catboost training on crop-type decadal data
- [x]  Presto FT on (crop/no-crop) monthly data + Catboost training on crop-type monthly data
- [x]  Presto FT on (crop/no-crop) decadal data + Catboost training on crop-type decadal data 
- [x] Self-Supervised trained Presto on monthly data (#64 ) + Catboost training on crop-type monthly data
- [x] Self-Supervised trained Presto on decadal data (#64) + Catboost training on crop-type decadal data

**Comment by giollimirgia** [comment]
**Presto FT on (crop/no-crop) monthly data + Catboost training on crop-type monthly data**

```
              precision    recall  f1-score   support

   110101000       0.48      0.56      0.52     12801
   110102000       0.56      0.30      0.39     10744
   110103000       0.10      0.30      0.15       731
   110106000       0.48      0.78      0.60      6790
   110107000       0.06      0.00      0.00       592
   110600001       0.87      0.25      0.38     13916
   110600002       0.18      0.46      0.26       235
   110600003       0.99      0.64      0.78     14296
   119999999       0.27      0.69      0.39      8058

    accuracy                           0.50     68163
   macro avg       0.45      0.44      0.39     68163
weighted avg       0.65      0.50      0.51     68163

 f1_score: 0.3856634547348625
```

<img src=https://github.com/WorldCereal/presto-worldcereal/assets/49987400/531993e9-906a-43b1-bdbc-2f49035e6e3a alt="image" width="550" height="400">

**Comment by giollimirgia** [comment]
**Presto FT on (crop/no-crop) decadal data + Catboost training on crop-type decadal data**

```
              precision    recall  f1-score   support

   110101000       0.44      0.47      0.46     12801
   110102000       0.51      0.27      0.35     10744
   110103000       0.18      0.22      0.20       731
   110106000       0.30      0.82      0.44      6790
   110107000       0.34      0.15      0.21       592
   110600001       0.90      0.15      0.25     13916
   110600002       0.24      0.13      0.17       235
   110600003       0.99      0.56      0.72     14296
   119999999       0.27      0.64      0.38      8058

    accuracy                           0.44     68163
   macro avg       0.47      0.38      0.35     68163
weighted avg       0.62      0.44      0.44     68163

 f1_score: 0.3540460669977847
```

<img src=https://github.com/WorldCereal/presto-worldcereal/assets/49987400/6150202e-9e1b-431d-88fe-124f731c9195 alt="image" width="550" height="400">

**Comment by giollimirgia** [comment]
**Pretrained Presto (not fine tuned) + Catboost training on crop-type decadal data**

```
              precision    recall  f1-score   support

   110101000       0.48      0.38      0.42     12801
   110102000       0.48      0.29      0.36     10744
   110103000       0.05      0.38      0.10       731
   110106000       0.46      0.70      0.55      6790
   110107000       0.24      0.76      0.37       592
   110600001       0.82      0.12      0.22     13916
   110600002       0.08      0.09      0.09       235
   110600003       0.93      0.57      0.71     14296
   119999999       0.21      0.59      0.30      8058

    accuracy                           0.41     68163
   macro avg       0.42      0.43      0.35     68163
weighted avg       0.60      0.41      0.42     68163

 f1_score: 0.3466335894838581
```

<img src=https://github.com/WorldCereal/presto-worldcereal/assets/49987400/93dd6460-f083-4f63-9cdd-0884ea2772f8 alt="image" width="550" height="400">

**Comment by giollimirgia** [comment]
Experiment F1 score summary 

![image](https://github.com/WorldCereal/presto-worldcereal/assets/49987400/c88b2170-3d60-41c2-9c00-2af66ee5fd5c)

**Comment by giollimirgia** [comment]
Experiment F1 score summary 

![image](https://github.com/WorldCereal/presto-worldcereal/assets/49987400/b037d23f-f4d2-4779-b64b-df80d0a51fd8)

**Comment by gabrieltseng** [comment]
Closing - summary in #63
