### ISSUE TITLE
Compare 30D to 10D Presto on crop-type classification task

### ISSUE THREAD

**Issue by giollimirgia** [WorldCereal/presto-worldcereal#63]
We ran preliminary experiments to compare Presto performance when fine-tuned on decadal and monthly data in the context of crop/no-crop classification (#52)
We now want to validate our conclusions in on crop-type classification task, where we expect to see a more significant difference between performance of Presto fine-tuned on decadal and monthly data.

- [ ] Spatial tests #59 
- [ ] Temporal tests  #61
- [ ] Stratified tests #62

**Comment by giollimirgia** [comment]
We still have to run the experiments with the 10D Presto trained in Self-Supervised mode and fine-tuned on crop type. 
This is the overview of what we got so far:

**Performance comparison**
<img src=https://github.com/WorldCereal/presto-worldcereal/assets/49987400/5e71b37c-85d3-4e14-a1bf-c62fca2e79a5 alt="image" width="800" height="250">

 **Performance per-class comparison**
<img src=https://github.com/WorldCereal/presto-worldcereal/assets/49987400/e40d79cc-90ad-4210-9155-b8254aa5f470
alt="image" width="800" height="400">

**Comment by gabrieltseng** [comment]
Closing as done
