### ISSUE TITLE
Presto Self-Supervised training with WorldCereal 30D and 10D data

### ISSUE THREAD

**Issue by giollimirgia** [WorldCereal/presto-worldcereal#64]
In our previous experiments we fine-tuned Presto in a supervised fashion for achieving a better performance on specific tasks such as crop/no-crop classification. However, we want to assess Presto ability to generalize on similar data but for a different classification task from the one it was fine-tuned on. Therefore, we aim to train Presto in a self-supervised modality so that the model could learn to extrapolate rich information embedded in the WorldCereal data in an unbiased way.

- [x] SS Training on 30D WorldCereal data
- [x] SS Training on 10D WorldCereal data  (after #66 )

Next step will be using the encoders of the resulting models to repeat the tests listed in #63 to compare not only the effect of 10D vs 30D data but also the impact of different versions of Presto on the performance achieved

**Comment by gabrieltseng** [comment]
Closing - results are in referenced issues
