### ISSUE TITLE
update Presto for Self-Supervised training on 10D WorldCereal data

### ISSUE THREAD

**Issue by giollimirgia** [WorldCereal/presto-worldcereal#66]
working on [decadal-ss-training](https://github.com/WorldCereal/presto-worldcereal/tree/decadal-ss-training)  branch

**Comment by giollimirgia** [comment]
working on [decadal-ss-training](https://github.com/WorldCereal/presto-worldcereal/tree/decadal-ss-training)  branch

**Comment by gabrieltseng** [comment]
Based on the results in #63, we will not merge #75 into main
