### ISSUE TITLE
Collect all the relevant Presto and CatBoost models for the future use

### ISSUE THREAD

**Issue by cbutsko** [WorldCereal/presto-worldcereal#68]
The following steps need to be done:

- [x] a relevant repository in the Artifactory need to be chosen to store the models - `auxdata-public/worldcereal/models/PhaseII/`
- [x] naming convention for models need to be established
- [ ] a list of all models required need to be compiled:
    - [ ] Presto SS on 30D WorldCereal
    - [ ] Presto SS on 10D WorldCereal
    - [ ] original Presto FT (from stratified task) on 30D WorldCereal for cropland
    - [ ] original Presto FT (from stratified task) on 10D WorldCereal for cropland

**Comment by cbutsko** [comment]
The following naming convention is proposed:
`{model_type}_{compositing_window}_{task_type}_{test_type}`

where

- _model_type_:
    - presto: Base Presto (didn’t see any WorldCereal data)
    - presto-ft-cl: Base Presto finetuned with WorldCereal data 
    - presto-ss-wc: Base Presto which was then up-trained in a self-supervised manner with all available WorldCereal data 
    - presto-ss-wc-ft-ct: Base Presto which was then up-trained in a self-supervised manner with all available WorldCereal data, and then was fine tuned using crop type data
- _compositing_window:_
    - 10D
    - 30D
- _task_type:_ 
    - cropland
    - croptype
- _task_type:_ 
    - random
    - spatial
    - temporal
    - seasonal

**Comment by gabrieltseng** [comment]
Closing as done. 

If new models are trained, send the model to @cbutsko so that it can be uploaded to the artefactory
